<a href="https://colab.research.google.com/github/2naayoon/pandas/blob/main/%EB%84%98%ED%8C%8C%EC%9D%B4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### 넘파이
- 과학 계산 및 수학 계산 라이브러리
- 이미지와 컴퓨터 그래픽을 빠르게 처리
- 반복문 작성하지 않고 전체 데이터 배열을 빠르게 계산할 수 있는 수학 함수 제공

> 넘파이 배열
- 벡터(1차원)와 매트릭스(2차원)를 배열이라고 함
- 머신러닝에서 사용하는 주요 데이터 구조
  - 데이터 학습 시 주는 이미지 → 01011...

In [104]:
import numpy as np

### 1. 1차원 배열(벡터)

In [105]:
array1 = np.array([1,2,3,4])
array1

array([1, 2, 3, 4])

In [106]:
array1.shape

(4,)

### 2. 2차원 배열(매트릭스)

In [107]:
data1 = [
    [1,2,3],
    [4,5,6]
]
array2 = np.array(data1)
array2

array([[1, 2, 3],
       [4, 5, 6]])

In [108]:
array2.shape

(2, 3)

In [109]:
# 대괄호 개수 = 차원 개수 (3개까지 늘어남)
array3 = np.array([[1,2,3,4]])
array3.shape

(1, 4)

In [110]:
# ndim : 차원 수 알아보기

print(array1.ndim)
print(array2.ndim)
print(array3.ndim)

1
2
2


In [111]:
# 파이썬에서는 리스트는 서로 다른 타입 가짐

list1 = [1,2,"a",3.5]
list1

[1, 2, 'a', 3.5]

In [112]:
# numpy 는 하나의 타입으로 변경해서 array 생성

np.array(list1)

array(['1', '2', 'a', '3.5'], dtype='<U32')

In [113]:
# array1.dtype

# 타입변환 - pandas 에서 변환 / astype() 변환
# float64 : float 를 64비트로 표현 (8바이트)
# float : 4byte
# double : 8byte (float64 = double)
array_f1 = array1.astype("float64")
array_f1.dtype

dtype('float64')

### 3. 넘파이 함수

In [114]:
# arange(n) : 0 ~ n-1 해당하는 넘파이 배열 생성

np.arange(10)

np.arange(5, 10)

np.arange(1, 10, 2)

array([1, 3, 5, 7, 9])

In [115]:
# 5의 배수 넘파이 배열 생성
np.arange(5,101,5)

array([  5,  10,  15,  20,  25,  30,  35,  40,  45,  50,  55,  60,  65,
        70,  75,  80,  85,  90,  95, 100])

In [116]:
# zeros(n) : n 개만큼 0을 채워서 넘파이 1차원 배열 생성 (기본 float 타입)
# zeros(행, 열) : 2차원 배열 생성

np.zeros(4)

np.zeros((3,4))

np.zeros((3,4,2))

array([[[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]]])

In [117]:
# ones(n) : n개만큼 1을 채워서 넘파이 1차원 배열 생성

np.ones(4)

np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [118]:
# np.empty() : 임의의 값을 넣어줌

np.empty(4)
np.empty((3,4), dtype=int)

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [119]:
# np.full() : 특정한 값으로 채워진 넘파이 배열 생성

np.full(4, fill_value=7)
np.full((2,4), fill_value=5)

array([[5, 5, 5, 5],
       [5, 5, 5, 5]])

In [120]:
# np.eye(n)

np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [121]:
# np.linspace(시작, 끝, 전체개수) : 시작과 끝 범위에서 균등하게 분할된 값으로 반환

np.linspace(1,10,5)
np.linspace(1,10,4)

array([ 1.,  4.,  7., 10.])

In [122]:
# np.random.rand(n) : 0 ~ 1 사이

np.random.rand(2,3)

array([[0.18311175, 0.50355505, 0.97588764],
       [0.21490002, 0.59912092, 0.90698919]])

In [123]:
# np.random.randn() : 정규분포로 샘플링 된 배열 생성
np.random.randn(5)
np.random.randn(3,4)

array([[ 0.67904359, -0.86189082, -0.60542449, -0.57966623],
       [ 0.40824139, -0.7299122 ,  0.80001301, -0.67359655],
       [ 0.58912829, -0.46740728,  0.07614012, -0.20123415]])

In [124]:
# np.random.randint(시작, 마지막, 개수) : 특정 범위 안의 숫자 추출

np.random.randint(1,10, 5)

array([1, 7, 2, 6, 8])

In [125]:
# np.random.seed(임의의 숫자) : random 사용 시 실행 때마다 결과가 다르게 나오는 것을 방지

np.random.seed(140)
np.random.randn(2,3)

array([[-0.46716782,  0.29599552,  0.18548011],
       [-0.82809842, -0.03192753,  1.00155352]])

In [126]:
# np.random.choice(n) : 0 ~ n-1 까지 임의의 수 추출
np.random.choice(100)
np.random.choice(100, size=(3,4))

array([[44, 47, 66, 75],
       [ 5, 36, 36, 40],
       [13, 84, 33, 67]])

### 4. 인덱싱과 슬라이싱

In [127]:
arr1 = np.arange(1,10)
arr1

print(arr1[2])
print(arr1[-2])

arr1[3] = 18
arr1

3
8


array([ 1,  2,  3, 18,  5,  6,  7,  8,  9])

In [128]:
# reshape()

arr1 = np.arange(1,10).reshape(3,3)

In [129]:
print(arr1[0,0])
print(arr1[1,1])

1
5


In [130]:
# 3차원 : 텐서

arr1 = np.arange(36).reshape(3,4,3)
arr1

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]],

       [[12, 13, 14],
        [15, 16, 17],
        [18, 19, 20],
        [21, 22, 23]],

       [[24, 25, 26],
        [27, 28, 29],
        [30, 31, 32],
        [33, 34, 35]]])

In [131]:
arr1[0]

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [132]:
arr1[0,1]

array([3, 4, 5])

In [133]:
arr1[0,1,-1]

5

In [134]:
# 16 출력
arr1[1,1,1]

16

In [135]:
arr1 = np.arange(1,10)
arr1

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [136]:
arr1[0:3]
arr1[:3]
arr1[3:]

array([4, 5, 6, 7, 8, 9])

In [137]:
arr1 = np.arange(1,10).reshape(3,3)
arr1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [138]:
arr1[:2,:1]

array([[1],
       [4]])

In [139]:
arr1[1:3,:]

array([[4, 5, 6],
       [7, 8, 9]])

In [140]:
arr1 = np.arange(1,10)
arr1

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [141]:
arr1[arr1 > 5]

array([6, 7, 8, 9])

### 데이터 형태 변경

In [142]:
y = np.arange(15).reshape(3,5)
y

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [143]:
y.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [144]:
# 2*3 5개

x = np.arange(30).reshape(2,3,5)
x

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]],

       [[15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29]]])

In [145]:
x.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

### ndarray 기본 함수
- add(), subtract(), multiply(), divide() 기본함수 제공

In [146]:
x = np.array([[4,4,4],[8,8,8]])
y = np.array([[1,1,1],[2,2,2]])

In [147]:
x + y

array([[ 5,  5,  5],
       [10, 10, 10]])

In [148]:
x - y

array([[3, 3, 3],
       [6, 6, 6]])

In [149]:
x * y

array([[ 4,  4,  4],
       [16, 16, 16]])

In [150]:
x / y

array([[4., 4., 4.],
       [4., 4., 4.]])

In [151]:
np.add(x,y)

array([[ 5,  5,  5],
       [10, 10, 10]])

In [152]:
np.subtract(x,y)

array([[3, 3, 3],
       [6, 6, 6]])

In [153]:
np.multiply(x, y)

array([[ 4,  4,  4],
       [16, 16, 16]])

In [154]:
np.divide(x, y)

array([[4., 4., 4.],
       [4., 4., 4.]])

In [155]:
x = np.random.rand(15)
x

array([0.73691749, 0.8361513 , 0.15280743, 0.50877979, 0.90080608,
       0.25138757, 0.16394773, 0.59597188, 0.99107897, 0.41354387,
       0.31160974, 0.74089766, 0.14398804, 0.53811173, 0.62095789])

In [156]:
x.mean()

0.5271304791924293

In [157]:
# 최대값의 인덱스

x.argmax()

8

In [158]:
x.std()

0.2718192305311343

In [159]:
x.sum()

7.906957187886439

In [160]:
# 이전 요소 덧셈합
x.cumsum()

array([0.73691749, 1.5730688 , 1.72587623, 2.23465602, 3.1354621 ,
       3.38684967, 3.5507974 , 4.14676928, 5.13784825, 5.55139212,
       5.86300186, 6.60389952, 6.74788757, 7.2859993 , 7.90695719])